parameters:
    #parameter_name: value

services:
  use_case.add_demand:
      class: Application\UseCase\AddDemand
      arguments:
          - '@modules.theatrical_performance.demand.repository'

  use_case.read_demands:
      class: Application\UseCase\ReadDemands
      arguments:
          - '@modules.theatrical_performance.demand.repository'

  modules.theatrical_performance.demand.repository:
      class: Modules\TheatricalPerformance\Infrastructure\Persistence\Doctrine\DoctrineDemandRepository
      arguments:
          - '@doctrine.orm.default_entity_manager'
